# Site
site_name: 广财信息学院生存指南
site_url: https://xeraphinite.github.io/Survive_CS_GDUFE/
site_description: 烂尾楼下，学生的自救与苟延残喘

# Repository
repo_name: Xeraphinite/Survive_CS_GDUFE
repo_url: https://github.com/Xeraphinite/Survive_CS_GDUFE

# Copyright
copyright: Copyright &copy; 2022-2023 SOF_Vanquishers

#

# Theme Configuration
theme:
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github-alt
    logo: material/run
  font:
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.index
    - navigation.top
    - navigation.footer

# Plugins
plugins:
  - tags


# Markdown Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Page Tree
nav:
  - GDUFE 信息学院生存指南: index.md
  - 瞬息全信院:
      - ACM 基本介绍: everything_everywhere_all_at_sof/ACM.md
      - CS 书籍推荐与锐评: everything_everywhere_all_at_sof/CS书籍推荐与锐评.md
  - 宇宙财介绍:
      - 宇宙财基本介绍: gdufe_information/广财的基本介绍.md
      - 佛山校区吃饭指南: gdufe_information/佛山校区吃饭指南.md
      - 广州校区吃饭指南: gdufe_information/广州校区吃饭指南.md
      - 关于 GPA、保研和考研: gdufe_information/关于GPA、保研和考研.md