# Site
site_name: 广财信息学院生存指南
site_url: https://xeraphinite.github.io/gdufe-cs-manual
site_description: 烂尾楼下，学生的苟延残喘与自救

# Repository
repo_name: Xeraphinite/gdufe-cs-manual
repo_url: https://github.com/Xeraphinite/gdufe-cs-manual

# Copyright
copyright: Copyright &copy; 2023-present SOF-Vanquishers

# Social Media
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xeraphinite/

# Theme Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github-alt
    logo: material/run
  font:
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.index
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight

# Plugins
plugins:
  - tags
  - search:
      lang: zh
  - git-revision-date-localized:
      enable_creation_date: true

# Markdown Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Page Tree
nav:
  - GDUFE 信息学院生存指南: index.md
  - 瞬息全信院:
      - 信息学院介绍: everything-everywhere-all-at-sof/index.md
      - ACM 介绍: everything-everywhere-all-at-sof/ACM.md
      - CS 书籍推荐与锐评: everything-everywhere-all-at-sof/CS书籍推荐与锐评.md
      - 老师推荐与锐评: everything-everywhere-all-at-sof/老师推荐与锐评.md
      - 课程推荐与锐评: everything-everywhere-all-at-sof/课程推荐与锐评.md
      - 网络资源推荐与锐评: everything-everywhere-all-at-sof/网络资源推荐与锐评.md
      - 社团推荐与锐评: everything-everywhere-all-at-sof/社团推荐与锐评.md
      - 速通毕业设计: everything-everywhere-all-at-sof/速通毕业设计.md
  - 宇宙财介绍:
      - 宇宙财基本介绍: gdufe-information/index.md
      - 佛山校区吃饭指南: gdufe-information/佛山校区吃饭指南.md
      - 广州校区吃饭指南: gdufe-information/广州校区吃饭指南.md
      - 黑话指南: gdufe-information/黑话指南.md
      - 上课: gdufe-information/上课.md
      - 选课: gdufe-information/选课.md
      - 实习: gdufe-information/实习.md
      - 图书馆与借书: gdufe-information/图书馆与借书.md
      - 素拓: gdufe-information/素拓.md
      - GPA、保研和考研: gdufe-information/GPA、保研和考研.md
